tinyswoole.lo: /data/C_study/swoole/tinyswoole-master/tinyswoole.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/data/C_study/swoole/tinyswoole-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/C_study/swoole/tinyswoole-master/tinyswoole.c -o tinyswoole.lo 
tinyswoole_server.lo: /data/C_study/swoole/tinyswoole-master/tinyswoole_server.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/data/C_study/swoole/tinyswoole-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/C_study/swoole/tinyswoole-master/tinyswoole_server.c -o tinyswoole_server.lo 
src/log.lo: /data/C_study/swoole/tinyswoole-master/src/log.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/data/C_study/swoole/tinyswoole-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/C_study/swoole/tinyswoole-master/src/log.c -o src/log.lo 
src/socket.lo: /data/C_study/swoole/tinyswoole-master/src/socket.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/data/C_study/swoole/tinyswoole-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/C_study/swoole/tinyswoole-master/src/socket.c -o src/socket.lo 
src/network/server.lo: /data/C_study/swoole/tinyswoole-master/src/network/server.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/data/C_study/swoole/tinyswoole-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/C_study/swoole/tinyswoole-master/src/network/server.c -o src/network/server.lo 
src/network/reactor_thread.lo: /data/C_study/swoole/tinyswoole-master/src/network/reactor_thread.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/data/C_study/swoole/tinyswoole-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/C_study/swoole/tinyswoole-master/src/network/reactor_thread.c -o src/network/reactor_thread.lo 
src/network/process_pool.lo: /data/C_study/swoole/tinyswoole-master/src/network/process_pool.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/data/C_study/swoole/tinyswoole-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/C_study/swoole/tinyswoole-master/src/network/process_pool.c -o src/network/process_pool.lo 
src/network/worker.lo: /data/C_study/swoole/tinyswoole-master/src/network/worker.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/data/C_study/swoole/tinyswoole-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/C_study/swoole/tinyswoole-master/src/network/worker.c -o src/network/worker.lo 
src/reactor/epoll.lo: /data/C_study/swoole/tinyswoole-master/src/reactor/epoll.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/data/C_study/swoole/tinyswoole-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/C_study/swoole/tinyswoole-master/src/reactor/epoll.c -o src/reactor/epoll.lo 
src/reactor/base.lo: /data/C_study/swoole/tinyswoole-master/src/reactor/base.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/data/C_study/swoole/tinyswoole-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/C_study/swoole/tinyswoole-master/src/reactor/base.c -o src/reactor/base.lo 
src/pipe/unix_socket.lo: /data/C_study/swoole/tinyswoole-master/src/pipe/unix_socket.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/data/C_study/swoole/tinyswoole-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/C_study/swoole/tinyswoole-master/src/pipe/unix_socket.c -o src/pipe/unix_socket.lo 
$(phplibdir)/tinyswoole.la: ./tinyswoole.la
	$(LIBTOOL) --mode=install cp ./tinyswoole.la $(phplibdir)

./tinyswoole.la: $(shared_objects_tinyswoole) $(TINYSWOOLE_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_tinyswoole) $(TINYSWOOLE_SHARED_LIBADD)

